### Numpy

In [2]:
## Creating Array using numpy
## 1D array

import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [3]:
## Reshaping the above 1D array into a 2D array

arr2 = np.array([1, 2, 3, 4, 5])
arr2.reshape(1,5) 

array([[1, 2, 3, 4, 5]])

In [7]:
## Creating a 2D array
arr2 = np.array([[1, 2, 3 ,4, 5]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]]
(1, 5)


In [9]:
arr2 = np.array([[1,2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr2)
print(arr2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


Using built-in functions 

In [ ]:
## .arange()

np.arange(5)

array([0, 1, 2, 3, 4])

In [11]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [13]:
np.arange(1, 10, 2).reshape(5, 1)

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [ ]:
## .zeros() .ones()

np.ones(3)

array([1., 1., 1.])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [19]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
## creating an Identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
## Attributes of Numpy array

arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print(f"Shape: {arr.shape}")
print(f"Number of dimensions: {arr.ndim}")
print("Number of elements in the array: ", arr.size)
print("Data type: ", arr.dtype)
print("Item size(in bytes): ", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Number of elements in the array:  6
Data type:  int64
Item size(in bytes):  8


In [24]:
## Numpy Vectorized Operations

arr1 = np.array([1, 2, 3, 4 ,5])
arr2 = np.array([10, 20, 30, 40, 50])

## Element wise addition
print("Addition: ", arr1 + arr2)

## Element wise subtraction
print("Subtraction: ", arr1 - arr2)

## Element wise multiplication
print(f"Multiplication: {arr1 * arr2}")

## Element wise division
print(f"Division: {arr1/arr2}")

Addition:  [11 22 33 44 55]
Subtraction:  [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [3]:
## Universal functions

arr = np.array([1, 2, 3, 4, 5])

## Square root
print(np.sqrt(arr))

## Exponential 
print(np.exp(arr))

## sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


Array slicing and indexing

In [ ]:
## Accessing elements

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("Array:\n", arr)
print(arr[1])
print(arr[0][0])
print(arr[1:, 2:])

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8]
1
[[ 7  8]
 [11 12]]


In [ ]:
## Accessing first two rows
print(arr[0:2])

[[1 2 3 4]
 [5 6 7 8]]


In [15]:
## Accessing  3 4 7 8
print(arr[0:2, 2:])

[[3 4]
 [7 8]]


In [16]:
## Accessing 6 7 10 11
print(arr[1:, 1:3])

[[ 6  7]
 [10 11]]


In [22]:
print(arr[0, 0])

1


In [23]:
## Modifying elements

arr[0, 1] = 100
print(arr)

[[  1 100   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [24]:
arr[1:] = 50
print(arr)

[[  1 100   3   4]
 [ 50  50  50  50]
 [ 50  50  50  50]]


In [25]:
## Normalization
# It means to have mean 0 and standard deviation 1
data = np.array([1, 2, 3, 4, 5])

##Calculate mean and standard deviation 
mean = np.mean(data)
std_dev = np.std(data)

##Normalize the data
normalized_data = (data - mean)/std_dev
print(f"Normalized data: {normalized_data}")

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [27]:
## Mean, median, standard deviation and variance

data = np.arange(1,11)

## Mean
mean = np.mean(data)
print(f"Mean: {mean}")

## Median
median = np.median(data)
print(f"Median: {median}")

## Standard deviation
std_dev = np.std(data)
print(f"Standard deviation: {std_dev}")

## Variance
variance = np.var(data)
print(f"Variance: {variance}")


Mean: 5.5
Median: 5.5
Standard deviation: 2.8722813232690143
Variance: 8.25


In [30]:
## Logical operations 
data = np.arange(1, 9)

print(data>5)

[False False False False False  True  True  True]


In [33]:
## Retrieve all the elements greater than 5

print(data[data>5])
print(data[(data>=5) & (data<=8)])

[6 7 8]
[5 6 7 8]
