# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

Assignment 1

In [2]:
## 1
import numpy as np
import random

data = [random.randint(1, 20) for _ in range(25)]
arr1 = np.array(data).reshape(5, 5)
print("Original array:")
print(arr1)
arr1[:, 2] = 1
print("\nModified array:")
print(arr1)

Original array:
[[14  7 18 11 11]
 [17  2 11 14 16]
 [ 3  4  7 14 18]
 [20  3 13  4  3]
 [16  6  6 13  3]]

Modified array:
[[14  7  1 11 11]
 [17  2  1 14 16]
 [ 3  4  1 14 18]
 [20  3  1  4  3]
 [16  6  1 13  3]]


In [5]:
## 2
array = np.random.randint(1, 17, size=(4, 4))
print(array)

for i in range(4):
    array[i, i] = 0
print(array)

[[ 8  6 15  6]
 [16 14  4 16]
 [14  7  7 11]
 [ 2  4 15 14]]
[[ 0  6 15  6]
 [16  0  4 16]
 [14  7  0 11]
 [ 2  4 15  0]]


Assignment 2

In [ ]:
## 1
array = np.arange(1, 37).reshape(6, 6)
print("Original Array:")
print(array)

sub_array = array[2:5, 1:4] ## OR sub_array = array[2:5][1:4]
print("\nSub Array:")
print(sub_array)

Original Array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Sub Array:
[[19 20 21 22 23 24]
 [25 26 27 28 29 30]]


In [10]:
## 2
array = np.random.randint(1, 21, size=(5, 5))
print("Original Array:")
print(array)

border_elements = np.concatenate((array[0, :], array[-1, :], array[1:-1, 0], array[1:-1, -1]))
print("\nBorder Elements:")
print(border_elements)

Original Array:
[[18  9  5 14  2]
 [15  4 17  7  1]
 [14 10 19 18 13]
 [19 19  5 18  3]
 [13 13  4 12  7]]

Border Elements:
[18  9  5 14  2 13 13  4 12  7 15 14 19  1 13  3]


Assignment 3

In [13]:
## 1
arr1 = np.random.randint(1, 16, size=(3, 4))
arr2 = np.random.randint(1, 16, size=(3, 4))
print("First Array:")
print(arr1)
print("\nSecond Arrary:")
print(arr2)
print("\nAddition:\n", arr1 + arr2)
print("Subtraction:\n", arr1 - arr2)
print("Multiplication:\n", arr1 * arr2)
print("Division:\n", arr1/arr2)

First Array:
[[ 3 11 12  2]
 [14  2  7 10]
 [ 7  6 15  2]]

Second Arrary:
[[14 12  5  2]
 [ 3  9  9  4]
 [ 1 14 11  8]]

Addition:
 [[17 23 17  4]
 [17 11 16 14]
 [ 8 20 26 10]]
Subtraction:
 [[-11  -1   7   0]
 [ 11  -7  -2   6]
 [  6  -8   4  -6]]
Multiplication:
 [[ 42 132  60   4]
 [ 42  18  63  40]
 [  7  84 165  16]]
Division:
 [[0.21428571 0.91666667 2.4        1.        ]
 [4.66666667 0.22222222 0.77777778 2.5       ]
 [7.         0.42857143 1.36363636 0.25      ]]


In [15]:
## 2
array = np.arange(1, 17).reshape(4, 4)
print("Original Array:")
print(array)

row_sum = np.sum(array, axis=1)
column_sum = np.sum(array, axis=0)

print("Row-wise sum: ", row_sum)
print("Column-wise sum: ", column_sum)

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row-wise sum:  [10 26 42 58]
Column-wise sum:  [28 32 36 40]


Assignment 4

In [20]:
## 1
array = np.random.randint(1, 21, size=(5, 5))
print("Original Array:")
print(array)

mean = np.mean(array)
median = np.median(array)
standard_deviation = np.std(array)
variance = np.var(array)

print(f"Mena: {mean}")
print(f"Median: {median}")
print(f"Standard deviation: {standard_deviation}")
print(f"variance: {variance}")

Original Array:
[[ 8 15  4 17 18]
 [14 11 20  5 16]
 [14 10  4 16  4]
 [15  2  4  4 11]
 [15  2  9 16  1]]
Mena: 10.2
Median: 11.0
Standard deviation: 5.824087911424415
variance: 33.92


In [34]:
## 2
array = np.arange(1, 10).reshape(3, 3)
print("Original Array:")
print(array)

mean = np.mean(array)
standard_deviation = np.std(array)

normalized_array = (data - mean)/standard_deviation
print(f"Normalized array: {normalized_array}")

Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized array: [ 5.03487835  1.54919334  5.80947502  0.77459667  0.38729833  5.80947502
  5.80947502  2.32379001  4.64758002  2.32379001  5.80947502  0.77459667
 -1.54919334  4.64758002  4.64758002  3.48568501 -1.161895    4.26028168
  2.71108834  5.42217668  1.54919334 -0.38729833  5.42217668  3.87298335
  5.03487835]


Assignment 5

In [9]:
## 1
array = np.random.randint(1, 10, size=(3, 3))
print("Original Array")
print(array)

arr = np.random.randint(1, 10, size=(3, ))
print("\n1D Array")
print(arr)

## Adding 1D array to 2D array using broadcasting
result = array + arr
print("\nSum of both arrays:\n", result)

Original Array
[[7 3 8]
 [9 8 7]
 [6 6 3]]

1D Array
[2 6 1]

Sum of both arrays:
 [[ 9  9  9]
 [11 14  8]
 [ 8 12  4]]


In [11]:
## 2
array = np.random.randint(1, 11, size=(4, 4))
column_array = np.random.randint(1, 11, size=(4,))
print("Original array:")
print(array)
print("\n1D array:")
print(column_array)

result = array - column_array[:, np.newaxis]
print("\nResultant array:")
print(result)

Original array:
[[ 5  5  3  6]
 [ 8  8  7  8]
 [ 8  3  5  6]
 [ 2  4 10  1]]

1D array:
[ 6  7  3 10]

Resultant array:
[[-1 -1 -3  0]
 [ 1  1  0  1]
 [ 5  0  2  3]
 [-8 -6  0 -9]]


Assignment 6

In [8]:
## 1
matrix = np.random.randint(1, 11, size=(3, 3))
print("Matrix: ")
print(matrix)

## Determinant
determinant = np.linalg.det(matrix)
print(f"\nDeterminant: {determinant}")

## Inverse
inverse = np.linalg.inv(matrix)
print("\nInverse of matrix:")
print(inverse)

## Eigenvalues
eigenvalues = np.linalg.eigvals(matrix)
print(f"\nEigenvalues: {eigenvalues}")

## Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print(eigenvalues)
print(eigenvectors)

Matrix: 
[[2 7 3]
 [6 7 8]
 [5 1 3]]

Determinant: 92.99999999999994

Inverse of matrix:
[[ 0.13978495 -0.19354839  0.37634409]
 [ 0.23655914 -0.09677419  0.02150538]
 [-0.31182796  0.35483871 -0.30107527]]

Eigenvalues: [14.15893919+0.j         -1.07946959+2.32444275j -1.07946959-2.32444275j]
[14.15893919+0.j         -1.07946959+2.32444275j -1.07946959-2.32444275j]
[[-0.5306228 +0.j          0.50899128-0.3786844j   0.50899128+0.3786844j ]
 [-0.7894709 +0.j          0.18905275+0.33560974j  0.18905275-0.33560974j]
 [-0.30850467+0.j         -0.67018741+0.j         -0.67018741-0.j        ]]


In [3]:
## 2
arr1 = np.random.randint(1, 10, size=(2, 3))
print("First array:")
print(arr1)

arr2 = np.random.randint(1, 10, size=(3, 2))
print("Second array:")
print(arr2)

## Multiplication of arrays
mult_result = np.dot(arr1, arr2)
print("Muliplication result:")
print(mult_result)

First array:
[[3 7 5]
 [7 3 4]]
Second array:
[[9 9]
 [5 2]
 [8 3]]
Muliplication result:
[[102  56]
 [110  81]]


Assignment 7

In [6]:
## 1
array = np.arange(1, 10).reshape(3, 3)
print("Original array:")
print(array)

print("\n(9, 1) array:")
print(array.reshape(9, 1))

print("\n(1, 9) array:")
print(array.reshape(1, 9))

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

(9, 1) array:
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]

(1, 9) array:
[[1 2 3 4 5 6 7 8 9]]


In [16]:
## 2
array = np.random.randint(1, 10, size=(5, 5))
print("Original array:")
print(array)

flat_array = array.flatten()
print("\nFlattened array: ", flat_array)

normal_array = flat_array.reshape(5, 5)
print("\nAgain (5, 5) array: ")
print(normal_array)

Original array:
[[6 7 8 6 2]
 [9 4 3 6 3]
 [3 5 1 8 2]
 [8 4 6 2 6]
 [3 8 4 9 5]]

Flattened array:  [6 7 8 6 2 9 4 3 6 3 3 5 1 8 2 8 4 6 2 6 3 8 4 9 5]

Again (5, 5) array: 
[[6 7 8 6 2]
 [9 4 3 6 3]
 [3 5 1 8 2]
 [8 4 6 2 6]
 [3 8 4 9 5]]


Assignment 8

In [17]:
## 1
array = np.random.randint(1, 10, size=(5, 5))
print("Original array:")
print(array)

corners = array[[0, 0, -1, -1], [0, -1, 0, -1]]
print("Corner elements: ", corners)

Original array:
[[4 3 8 8 5]
 [1 1 9 3 8]
 [5 4 7 4 6]
 [4 5 7 5 6]
 [8 1 2 2 8]]
Corner elements:  [4 5 8 8]


In [26]:
## 2
arr = np.random.randint(1, 21, size=(4, 4))
print("Original array:")
print(arr)

arr[arr > 10] = 10
print("\nModifies array:")
print(arr)

Original array:
[[ 2  5 12  2]
 [ 9 16  2 12]
 [ 9 17 20 16]
 [20 17 16  6]]

Modifies array:
[[ 2  5 10  2]
 [ 9 10  2 10]
 [ 9 10 10 10]
 [10 10 10  6]]


Assignment 9

In [4]:
## 1
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([("Alice", 20, 56.8), ("Bob", 25, 70.5), ("Charlie", 30, 78.45)], dtype=data_type)
print("Original array:")
print(data)
print(type(data))

sorted_data = np.sort(data, order='age')
print("\nSorted array on the basis of age:")
print(sorted_data)

sorted_weight = np.sort(data, order='weight')
print("\nSorted array on the basis of weight")
print(sorted_weight)

Original array:
[('Alice', 20, 56.8 ) ('Bob', 25, 70.5 ) ('Charlie', 30, 78.45)]
<class 'numpy.ndarray'>

Sorted array on the basis of age:
[('Alice', 20, 56.8 ) ('Bob', 25, 70.5 ) ('Charlie', 30, 78.45)]

Sorted array on the basis of weight
[('Alice', 20, 56.8 ) ('Bob', 25, 70.5 ) ('Charlie', 30, 78.45)]


In [3]:
## 2
data_type = [('x', 'i4'), ('y', 'i4')]
coordinates = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print("Cordinates: ", coordinates)

euclid_distance = np.sqrt((coordinates['x'][:, np.newaxis] - coordinates['x'])**2 + \
                          (coordinates['y'][:, np.newaxis] - coordinates['y'])**2)
print("\nEuclidean distance:")
print(euclid_distance)
                          

Cordinates:  [(1, 2) (3, 4) (5, 6)]

Euclidean distance:
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


Assignment 10

In [90]:
## 1
import numpy.ma as ma
array = np.random.randint(1, 16, size=(4, 4))
print("Original array:")
print(array)

masked_array = ma.masked_greater(array, 10)
print("\nMasked array:")
print(masked_array)

unmasked_sum = masked_array.sum()
print("\nSum of Unmasked elements:", unmasked_sum)


Original array:
[[11  2  3  1]
 [ 4  5 12 15]
 [12 14 14 15]
 [ 4 11  3 14]]

Masked array:
[[-- 2 3 1]
 [4 5 -- --]
 [-- -- -- --]
 [4 -- 3 --]]

Sum of Unmasked elements: 22


In [95]:
## 2
array = np.random.randint(1, 21, size=(3, 3))
print("Original array")
print(array)

masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("\nMasked array:")
print(masked_array)

unmasked_mean = masked_array.mean()
masked_array = masked_array.filled(unmasked_mean)

print("\nModified array:")
print(masked_array)

Original array
[[ 9 19 17]
 [ 2 18 15]
 [ 2 13 19]]

Masked array:
[[-- 19 17]
 [2 -- 15]
 [2 13 --]]

Modified array:
[[11 19 17]
 [ 2 11 15]
 [ 2 13 11]]
