# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

Assignment 1

In [3]:
## 1
import numpy as np
import random

data = [random.randint(1, 20) for _ in range(25)]
arr1 = np.array(data).reshape(5, 5)
print("Original array:")
print(arr1)
arr1[:, 2] = 1
print("\nModified array:")
print(arr1)

Original array:
[[18  9 20  7  6]
 [20 20 11 17 11]
 [20  7  1 17 17]
 [14  2 16 12 19]
 [ 9  4 19 15 18]]

Modified array:
[[18  9  1  7  6]
 [20 20  1 17 11]
 [20  7  1 17 17]
 [14  2  1 12 19]
 [ 9  4  1 15 18]]


In [5]:
## 2
array = np.random.randint(1, 17, size=(4, 4))
print(array)

for i in range(4):
    array[i, i] = 0
print(array)

[[ 8  6 15  6]
 [16 14  4 16]
 [14  7  7 11]
 [ 2  4 15 14]]
[[ 0  6 15  6]
 [16  0  4 16]
 [14  7  0 11]
 [ 2  4 15  0]]


Assignment 2

In [7]:
## 1
array = np.arange(1, 37).reshape(6, 6)
print("Original Array:")
print(array)

sub_array = array[2:5, 1:4]
print("\nSub Array:")
print(sub_array)

Original Array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Sub Array:
[[14 15 16]
 [20 21 22]
 [26 27 28]]


In [10]:
## 2
array = np.random.randint(1, 21, size=(5, 5))
print("Original Array:")
print(array)

border_elements = np.concatenate((array[0, :], array[-1, :], array[1:-1, 0], array[1:-1, -1]))
print("\nBorder Elements:")
print(border_elements)

Original Array:
[[18  9  5 14  2]
 [15  4 17  7  1]
 [14 10 19 18 13]
 [19 19  5 18  3]
 [13 13  4 12  7]]

Border Elements:
[18  9  5 14  2 13 13  4 12  7 15 14 19  1 13  3]


Assignment 3

In [13]:
## 1
arr1 = np.random.randint(1, 16, size=(3, 4))
arr2 = np.random.randint(1, 16, size=(3, 4))
print("First Array:")
print(arr1)
print("\nSecond Arrary:")
print(arr2)
print("\nAddition:\n", arr1 + arr2)
print("Subtraction:\n", arr1 - arr2)
print("Multiplication:\n", arr1 * arr2)
print("Division:\n", arr1/arr2)

First Array:
[[ 3 11 12  2]
 [14  2  7 10]
 [ 7  6 15  2]]

Second Arrary:
[[14 12  5  2]
 [ 3  9  9  4]
 [ 1 14 11  8]]

Addition:
 [[17 23 17  4]
 [17 11 16 14]
 [ 8 20 26 10]]
Subtraction:
 [[-11  -1   7   0]
 [ 11  -7  -2   6]
 [  6  -8   4  -6]]
Multiplication:
 [[ 42 132  60   4]
 [ 42  18  63  40]
 [  7  84 165  16]]
Division:
 [[0.21428571 0.91666667 2.4        1.        ]
 [4.66666667 0.22222222 0.77777778 2.5       ]
 [7.         0.42857143 1.36363636 0.25      ]]


In [15]:
## 2
array = np.arange(1, 17).reshape(4, 4)
print("Original Array:")
print(array)

row_sum = np.sum(array, axis=1)
column_sum = np.sum(array, axis=0)

print("Row-wise sum: ", row_sum)
print("Column-wise sum: ", column_sum)

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row-wise sum:  [10 26 42 58]
Column-wise sum:  [28 32 36 40]


Assignment 4

In [20]:
## 1
array = np.random.randint(1, 21, size=(5, 5))
print("Original Array:")
print(array)

mean = np.mean(array)
median = np.median(array)
standard_deviation = np.std(array)
variance = np.var(array)

print(f"Mena: {mean}")
print(f"Median: {median}")
print(f"Standard deviation: {standard_deviation}")
print(f"variance: {variance}")

Original Array:
[[ 8 15  4 17 18]
 [14 11 20  5 16]
 [14 10  4 16  4]
 [15  2  4  4 11]
 [15  2  9 16  1]]
Mena: 10.2
Median: 11.0
Standard deviation: 5.824087911424415
variance: 33.92


In [34]:
## 2
array = np.arange(1, 10).reshape(3, 3)
print("Original Array:")
print(array)

mean = np.mean(array)
standard_deviation = np.std(array)

normalized_array = (data - mean)/standard_deviation
print(f"Normalized array: {normalized_array}")

Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized array: [ 5.03487835  1.54919334  5.80947502  0.77459667  0.38729833  5.80947502
  5.80947502  2.32379001  4.64758002  2.32379001  5.80947502  0.77459667
 -1.54919334  4.64758002  4.64758002  3.48568501 -1.161895    4.26028168
  2.71108834  5.42217668  1.54919334 -0.38729833  5.42217668  3.87298335
  5.03487835]


Assignment 5

In [ ]:
## 1
